services:
  backend:
    image: bardinpetr/itmo_is_lab_1:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://heliospg:5432/studs
      SPRING_DATASOURCE_USERNAME: s367079
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: s367079

  frontend:
    image: bardinpetr/itmo_is_lab_1_client:latest
    restart: always

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

  heliospg:
    image: nowsci/sshtunnel
    container_name: heliospg
    volumes:
      - ./.ssh/:/data/:ro
    environment:
      - TUNNEL_HOST=s367079@helios.cs.ifmo.ru
      - TUNNEL_PORT=2222
      - REMOTE_HOST=localhost
      - LOCAL_PORT=5432
      - REMOTE_PORT=5432
      - KEY=/data/id_rsa
    restart: always

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqconfig:/mosquitto/config:rw
      - ./mqdata:/mosquitto/data:rw
      - ./mqlog:/mosquitto/log:rw
