create table no_flight_zone
(
    id     bigint generated by default as identity,
    radius double precision not null,
    lat    double precision not null,
    lon    double precision not null
);

create table product_type
(
    id           bigint generated by default as identity,
    type         varchar(255)     not null,
    piece_weight double precision not null
);


create table type_of_drone
(
    id         bigint generated by default as identity,
    name       varchar(255)     not null,
    max_weight double precision not null
);


create table "user"
(
    id            bigint generated by default as identity,
    username      varchar(255),
    password_hash varchar(255),
    role          varchar(255)
);


create table medical_facility
(
    id                  bigint generated by default as identity,
    name                varchar(255)     not null,
    responsible_user_id bigint           not null,
    lat                 double precision not null,
    lon                 double precision not null
);

create table request
(
    id                  bigint generated by default as identity,
    user_id             bigint       not null,
    status              varchar(255) not null,
    medical_facility_id bigint       not null
);


create table request_entry
(
    id                 bigint generated by default as identity,
    request_id         bigint            not null,
    product_type_id    bigint            not null,
    quantity           integer           not null,
    fulfilled_quantity integer default 0 not null
);


create table warehouse
(
    id   bigint generated by default as identity,
    name varchar(255)     not null,
    lat  double precision not null,
    lon  double precision not null
);


create table warehouse_products
(
    quantity     integer not null,
    product_id   bigint  not null,
    warehouse_id bigint  not null
);


create table spring_session
(
    primary_id            char(36) not null,
    session_id            char(36) not null,
    creation_time         bigint   not null,
    last_access_time      bigint   not null,
    max_inactive_interval integer  not null,
    expiry_time           bigint   not null,
    principal_name        varchar(100)
);


create table spring_session_attributes
(
    session_primary_id char(36)     not null,
    attribute_name     varchar(200) not null,
    attribute_bytes    bytea        not null,
);


create table route
(
    id                  bigint generated by default as identity,
    warehouse_id        bigint not null,
    medical_facility_id bigint not null
);


create table flight_task
(
    id                  bigint generated by default as identity,
    request_id          bigint                  not null,
    status              varchar(255)            not null,
    product_type_id     bigint                  not null,
    warehouse_id        bigint,
    medical_facility_id bigint,
    quantity            integer                 not null,
    timestamp           timestamp default now() not null,
    route_id            bigint
);


create table drone
(
    id             bigint generated by default as identity,
    model_id       bigint           not null,
    status         varchar(255)     not null,
    flight_task_id bigint,
    lat            double precision not null,
    lon            double precision not null
);


create table route_point
(
    point_number integer          not null,
    lat          double precision not null,
    lon          double precision not null,
    route_id     bigint           not null
);
