-- liquibase formatted sql

-- changeset petr:1731836982888-1
CREATE TABLE drone
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model_id       BIGINT                                  NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    flight_task_id BIGINT,
    lat            DOUBLE PRECISION                        NOT NULL,
    lon            DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_drone PRIMARY KEY (id)
);

-- changeset petr:1731836982888-2
CREATE TABLE flight_task
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id          BIGINT                                  NOT NULL,
    status              VARCHAR(255)                            NOT NULL,
    product_type_id     BIGINT                                  NOT NULL,
    warehouse_id        BIGINT,
    medical_facility_id BIGINT,
    quantity            INTEGER                                 NOT NULL,
    CONSTRAINT pk_flighttask PRIMARY KEY (id)
);

-- changeset petr:1731836982888-3
CREATE TABLE medical_facility
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255)                            NOT NULL,
    responsible_user_id BIGINT,
    lat                 DOUBLE PRECISION                        NOT NULL,
    lon                 DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_medicalfacility PRIMARY KEY (id)
);

-- changeset petr:1731836982888-4
CREATE TABLE no_flight_zone
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    radius FLOAT                                   NOT NULL,
    lat    DOUBLE PRECISION                        NOT NULL,
    lon    DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_noflightzone PRIMARY KEY (id)
);

-- changeset petr:1731836982888-5
CREATE TABLE product_type
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    piece_weight FLOAT                                   NOT NULL,
    CONSTRAINT pk_producttype PRIMARY KEY (id)
);

-- changeset petr:1731836982888-6
CREATE TABLE request
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    status              VARCHAR(255)                            NOT NULL,
    medical_facility_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

-- changeset petr:1731836982888-7
CREATE TABLE request_entry
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id      BIGINT                                  NOT NULL,
    product_type_id BIGINT                                  NOT NULL,
    quantity        INTEGER                                 NOT NULL,
    CONSTRAINT pk_requestentry PRIMARY KEY (id)
);

-- changeset petr:1731836982888-8
CREATE TABLE rev_info
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    owner     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_rev_info PRIMARY KEY (id)
);

-- changeset petr:1731836982888-9
CREATE TABLE route_point
(
    flight_task_id BIGINT           NOT NULL,
    point_number   INTEGER          NOT NULL,
    lat            DOUBLE PRECISION NOT NULL,
    lon            DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_routepoint PRIMARY KEY (flight_task_id, point_number)
);

-- changeset petr:1731836982888-10
CREATE TABLE type_of_drone
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    max_weight FLOAT                                   NOT NULL,
    CONSTRAINT pk_typeofdrone PRIMARY KEY (id)
);

-- changeset petr:1731836982888-11
CREATE TABLE "user"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255),
    password_hash VARCHAR(255),
    role          VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

-- changeset petr:1731836982888-12
CREATE TABLE user_audit
(
    revision_id   BIGINT NOT NULL,
    revision_type SMALLINT,
    username      VARCHAR(255),
    password_hash VARCHAR(255),
    role          VARCHAR(255),
    id            BIGINT NOT NULL,
    CONSTRAINT pk_user_audit PRIMARY KEY (revision_id, id)
);

-- changeset petr:1731836982888-13
CREATE TABLE warehouse
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    lat  DOUBLE PRECISION                        NOT NULL,
    lon  DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_warehouse PRIMARY KEY (id)
);

-- changeset petr:1731836982888-14
CREATE TABLE warehouse_products
(
    quantity          INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL,
    product_id        BIGINT  NOT NULL,
    warehouse_id      BIGINT  NOT NULL,
    CONSTRAINT pk_warehouseproducts PRIMARY KEY (product_id, warehouse_id)
);

-- changeset petr:1731836982888-15
ALTER TABLE drone
    ADD CONSTRAINT FK_DRONE_ON_FLIGHT_TASK FOREIGN KEY (flight_task_id) REFERENCES flight_task (id);

-- changeset petr:1731836982888-16
ALTER TABLE drone
    ADD CONSTRAINT FK_DRONE_ON_MODEL FOREIGN KEY (model_id) REFERENCES type_of_drone (id);

-- changeset petr:1731836982888-17
ALTER TABLE flight_task
    ADD CONSTRAINT FK_FLIGHTTASK_ON_MEDICAL_FACILITY FOREIGN KEY (medical_facility_id) REFERENCES medical_facility (id);

-- changeset petr:1731836982888-18
ALTER TABLE flight_task
    ADD CONSTRAINT FK_FLIGHTTASK_ON_PRODUCT_TYPE FOREIGN KEY (product_type_id) REFERENCES product_type (id);

-- changeset petr:1731836982888-19
ALTER TABLE flight_task
    ADD CONSTRAINT FK_FLIGHTTASK_ON_REQUEST FOREIGN KEY (request_id) REFERENCES request (id);

-- changeset petr:1731836982888-20
ALTER TABLE flight_task
    ADD CONSTRAINT FK_FLIGHTTASK_ON_WAREHOUSE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id);

-- changeset petr:1731836982888-21
ALTER TABLE medical_facility
    ADD CONSTRAINT FK_MEDICALFACILITY_ON_RESPONSIBLE_USER FOREIGN KEY (responsible_user_id) REFERENCES "user" (id);

-- changeset petr:1731836982888-22
ALTER TABLE request_entry
    ADD CONSTRAINT FK_REQUESTENTRY_ON_PRODUCT_TYPE FOREIGN KEY (product_type_id) REFERENCES product_type (id);

-- changeset petr:1731836982888-23
ALTER TABLE request_entry
    ADD CONSTRAINT FK_REQUESTENTRY_ON_REQUEST FOREIGN KEY (request_id) REFERENCES request (id);

-- changeset petr:1731836982888-24
ALTER TABLE request
    ADD CONSTRAINT FK_REQUEST_ON_MEDICAL_FACILITY FOREIGN KEY (medical_facility_id) REFERENCES medical_facility (id);

-- changeset petr:1731836982888-25
ALTER TABLE request
    ADD CONSTRAINT FK_REQUEST_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

-- changeset petr:1731836982888-26
ALTER TABLE route_point
    ADD CONSTRAINT FK_ROUTEPOINT_ON_FLIGHT_TASK FOREIGN KEY (flight_task_id) REFERENCES flight_task (id);

-- changeset petr:1731836982888-27
ALTER TABLE user_audit
    ADD CONSTRAINT FK_USER_AUDIT_ON_REVISION FOREIGN KEY (revision_id) REFERENCES rev_info (id);

-- changeset petr:1731836982888-28
ALTER TABLE warehouse_products
    ADD CONSTRAINT FK_WAREHOUSEPRODUCTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product_type (id);

-- changeset petr:1731836982888-29
ALTER TABLE warehouse_products
    ADD CONSTRAINT FK_WAREHOUSEPRODUCTS_ON_WAREHOUSE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id);

