-- liquibase formatted sql

-- changeset petr:table_route
CREATE TABLE route
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    warehouse_id        BIGINT                                  NOT NULL,
    medical_facility_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_route PRIMARY KEY (id)
);

-- changeset petr:flight_task_refer_route
ALTER TABLE flight_task
    ADD route_id BIGINT;

ALTER TABLE flight_task
    ADD CONSTRAINT FK_FLIGHTTASK_ON_ROUTE FOREIGN KEY (route_id) REFERENCES route (id);

-- changeset petr:route_point_refer_route
ALTER TABLE route_point
    ADD route_id BIGINT;

ALTER TABLE route_point
    ADD CONSTRAINT FK_ROUTEPOINT_ON_ROUTE FOREIGN KEY (route_id) REFERENCES route (id);

-- changeset petr:table_route_src_dst_refs
ALTER TABLE route
    ADD CONSTRAINT FK_ROUTE_ON_MEDICAL_FACILITY FOREIGN KEY (medical_facility_id) REFERENCES medical_facility (id),
    ADD CONSTRAINT FK_ROUTE_ON_WAREHOUSE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id);

-- changeset petr:route_point_unlink_with_task
ALTER TABLE route_point
    DROP CONSTRAINT fk_routepoint_on_flight_task,
    DROP COLUMN flight_task_id;

-- changeset petr:route_point_link_with_route
ALTER TABLE route_point
    ADD CONSTRAINT pk_routepoint PRIMARY KEY (route_id, point_number);
