# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateNoFlightZones = channel.unary_unary(
                '/ru.bardinpetr.itmo.meddelivery.app.service.router.RouterService/UpdateNoFlightZones',
                request_serializer=service__pb2.UpdateNoFlightZonesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.PlanRoute = channel.unary_unary(
                '/ru.bardinpetr.itmo.meddelivery.app.service.router.RouterService/PlanRoute',
                request_serializer=service__pb2.PlanRouteRequest.SerializeToString,
                response_deserializer=service__pb2.PlanRouteResponse.FromString,
                _registered_method=True)


class RouterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateNoFlightZones(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateNoFlightZones': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNoFlightZones,
                    request_deserializer=service__pb2.UpdateNoFlightZonesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PlanRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanRoute,
                    request_deserializer=service__pb2.PlanRouteRequest.FromString,
                    response_serializer=service__pb2.PlanRouteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ru.bardinpetr.itmo.meddelivery.app.service.router.RouterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ru.bardinpetr.itmo.meddelivery.app.service.router.RouterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateNoFlightZones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ru.bardinpetr.itmo.meddelivery.app.service.router.RouterService/UpdateNoFlightZones',
            service__pb2.UpdateNoFlightZonesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ru.bardinpetr.itmo.meddelivery.app.service.router.RouterService/PlanRoute',
            service__pb2.PlanRouteRequest.SerializeToString,
            service__pb2.PlanRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
