# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x31ru.bardinpetr.itmo.meddelivery.app.service.router\x1a\x1bgoogle/protobuf/empty.proto\"!\n\x05Point\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"n\n\x0cNoFlightZone\x12H\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x38.ru.bardinpetr.itmo.meddelivery.app.service.router.Point\x12\x14\n\x0cradiusMeters\x18\x02 \x01(\x01\"l\n\x1aUpdateNoFlightZonesRequest\x12N\n\x05zones\x18\x01 \x03(\x0b\x32?.ru.bardinpetr.itmo.meddelivery.app.service.router.NoFlightZone\"\xa0\x01\n\x10PlanRouteRequest\x12\x45\n\x03src\x18\x01 \x01(\x0b\x32\x38.ru.bardinpetr.itmo.meddelivery.app.service.router.Point\x12\x45\n\x03\x64st\x18\x02 \x01(\x0b\x32\x38.ru.bardinpetr.itmo.meddelivery.app.service.router.Point\"\\\n\x11PlanRouteResponse\x12G\n\x05route\x18\x01 \x03(\x0b\x32\x38.ru.bardinpetr.itmo.meddelivery.app.service.router.Point2\xa6\x02\n\rRouterService\x12|\n\x13UpdateNoFlightZones\x12M.ru.bardinpetr.itmo.meddelivery.app.service.router.UpdateNoFlightZonesRequest\x1a\x16.google.protobuf.Empty\x12\x96\x01\n\tPlanRoute\x12\x43.ru.bardinpetr.itmo.meddelivery.app.service.router.PlanRouteRequest\x1a\x44.ru.bardinpetr.itmo.meddelivery.app.service.router.PlanRouteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT']._serialized_start=97
  _globals['_POINT']._serialized_end=130
  _globals['_NOFLIGHTZONE']._serialized_start=132
  _globals['_NOFLIGHTZONE']._serialized_end=242
  _globals['_UPDATENOFLIGHTZONESREQUEST']._serialized_start=244
  _globals['_UPDATENOFLIGHTZONESREQUEST']._serialized_end=352
  _globals['_PLANROUTEREQUEST']._serialized_start=355
  _globals['_PLANROUTEREQUEST']._serialized_end=515
  _globals['_PLANROUTERESPONSE']._serialized_start=517
  _globals['_PLANROUTERESPONSE']._serialized_end=609
  _globals['_ROUTERSERVICE']._serialized_start=612
  _globals['_ROUTERSERVICE']._serialized_end=906
# @@protoc_insertion_point(module_scope)
